packages:
  - apps/*
  - packages/*

catalog:
  '@sanity/client': ^7.14.0
  '@types/node': ^24.10.9
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  lucide-react: 'catalog:'
  next-themes: 'catalog:'
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: 5.9.2
  zod: 'catalog:'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
